# Ejercicio con series de tiempo

In [ ]:
## ligas ejercicio
##http://www.aire.cdmx.gob.mx/default.php?opc=%27aqBjnmU=%27
##http://www.aire.cdmx.gob.mx/descargas/monitoreo/normatividad/NADF-009-AIRE-2017.pdf
##http://www.aire.cdmx.gob.mx/estadisticas-consultas/descargas/INDICExls-csv.pdf

### Indice de calidad de aire

In [8]:
import pandas as pd

##libreria para manejar directorios o archivos
import os

In [4]:
## lectura de archivos

data_24 = pd.read_csv(r'./Original_dataset/imeca2024.csv')

In [18]:
data_24.head()

,Fecha,Hora,Noroeste ozono,Noroeste dióxido de azufre,Noroeste dióxido de nitrógeno,Noroeste monóxido de carbono,Noroeste PM10,Noroeste PM25,Noreste ozono,Noreste dióxido de azufre,...,Suroeste dióxido de nitrógeno,Suroeste monóxido de carbono,Suroeste PM10,Suroeste PM25,Sureste ozono,Sureste dióxido de azufre,Sureste dióxido de nitrógeno,Sureste monóxido de carbono,Sureste PM10,Sureste PM25
0,01/01/2024,1,16.0,14,20.0,14.0,87,78.0,15.0,8,...,15.0,11.0,38,64,21.0,4,21.0,15.0,71.0,77
1,01/01/2024,2,9.0,14,20.0,15.0,94,82.0,10.0,8,...,14.0,11.0,40,67,11.0,4,20.0,15.0,77.0,85
2,01/01/2024,3,9.0,12,19.0,15.0,101,87.0,4.0,8,...,16.0,12.0,40,67,5.0,6,21.0,16.0,81.0,94
3,01/01/2024,4,12.0,12,19.0,16.0,105,89.0,5.0,10,...,14.0,12.0,45,70,4.0,6,20.0,17.0,97.0,106
4,01/01/2024,5,11.0,12,18.0,16.0,107,91.0,5.0,10,...,12.0,12.0,50,70,6.0,6,19.0,17.0,103.0,117

In [14]:
carpeta = r'./Original_dataset'

In [29]:
dataframe = []

##ciclo para traer todos los archivos
for archivo in os.listdir(carpeta):
    df = pd.read_csv(carpeta + '/' + archivo)
    columnas_primarias = ['Fecha','Hora']
    zonas = ['Noreste','Noroeste','Centro','Suroeste','Sureste']
    for zonas in zonas:
        columnas_primarias.append(f'{zonas} PM10')
        columnas_primarias.append(f'{zonas} monóxido de carbono')
    df_interes = df[columnas_primarias]
    dataframe.append(df_interes)

df_total = pd.concat(dataframe,ignore_index= True)

In [30]:
df_total

,Fecha,Hora,Noreste PM10,Noreste monóxido de carbono,Noroeste PM10,Noroeste monóxido de carbono,Centro PM10,Centro monóxido de carbono,Suroeste PM10,Suroeste monóxido de carbono,Sureste PM10,Sureste monóxido de carbono
0,01/01/2016,1,117,16.0,108,13.0,107,16.0,67,9.0,107.0,11.0
1,01/01/2016,2,122,18.0,110,13.0,107,17.0,70,9.0,107.0,12.0
2,01/01/2016,3,124,19.0,113,14.0,109,18.0,76,10.0,108.0,13.0
3,01/01/2016,4,126,19.0,115,14.0,110,19.0,83,10.0,107.0,14.0
4,01/01/2016,5,127,20.0,116,15.0,112,17.0,90,11.0,108.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...
69318,29/06/2024,13,39,7.0,39,8.0,35,8.0,23,7.0,26.0,6.0
69319,29/06/2024,14,39,7.0,39,8.0,35,8.0,23,7.0,28.0,6.0
69320,29/06/2024,15,39,6.0,39,7.0,35,7.0,23,6.0,28.0,6.0
69321,29/06/2024,16,39,6.0,36,6.0,35,7.0,24,6.0,28.0,5.0
69322,29/06/2024,17,39,6.0,34,6.0,34,6.0,24,6.0,30.0,5.0

In [39]:
df_total.describe()

,Hora,Noreste PM10,Noreste monóxido de carbono,Noroeste PM10,Noroeste monóxido de carbono,Centro PM10,Centro monóxido de carbono,Suroeste PM10,Suroeste monóxido de carbono,Sureste PM10,Sureste monóxido de carbono
count,69323.000000,68898.000000,66728.000000,69248.000000,66645.000000,69299.000000,66869.000000,69035.000000,66637.000000,66649.000000,66564.000000
mean,12.499834,75.792635,7.008842,68.102082,5.946163,58.192499,6.246975,42.509828,4.523988,64.173116,5.715236
std,6.921911,28.829598,4.058057,24.447218,3.294260,23.352578,3.439650,17.345446,2.133077,26.483766,3.029051
min,1.000000,9.000000,0.000000,11.000000,0.000000,9.000000,0.000000,6.000000,0.000000,4.000000,0.000000
25%,7.000000,51.000000,5.000000,48.000000,4.000000,40.000000,4.000000,30.000000,3.000000,43.000000,4.000000
50%,12.000000,77.000000,6.000000,65.000000,5.000000,55.000000,5.000000,40.000000,4.000000,63.000000,5.000000
75%,18.000000,102.000000,9.000000,88.000000,7.000000,74.000000,8.000000,52.000000,5.000000,86.000000,7.000000
max,24.000000,166.000000,64.000000,142.000000,43.000000,140.000000,52.000000,115.000000,25.000000,132.000000,36.000000

In [38]:
## reemplazo de valores

import numpy as np

df_total.replace(-99,np.nan,inplace=True)

In [47]:
## validacion de valores numericos
for col in df_total.columns[1:]:
    df_total[col] = pd.to_numeric(df_total[col],errors='coerce')

##convertir fecha en un valor valido para pandas
df_total['Fecha']=pd.to_datetime(df_total['Fecha'],format = '%d/%m/%Y')

In [ ]:
df.head()
df_total.set_index('Fecha''hora',inplace=True)

In [ ]:
df_total.isnull().sum()

In [55]:
## para ver distribucion de valores nulos
%pip install missingno

Requirement already satisfied: missingno in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (0.5.2)
Requirement already satisfied: numpy in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from missingno) (2.0.0)
Requirement already satisfied: matplotlib in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from missingno) (3.9.0)
Requirement already satisfied: scipy in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from missingno) (1.14.0)
Requirement already satisfied: seaborn in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from missingno) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from matplotlib->missingno) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from matplotlib->missingno) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from matplotlib->missingno) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from matplotlib->missingno) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from matplotlib->missingno) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from matplotlib->missingno) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from matplotlib->missingno) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from matplotlib->missingno) (2.9.0)
Requirement already satisfied: pandas>=1.2 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from seaborn->missingno) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from pandas>=1.2->seaborn->missingno) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from pandas>=1.2->seaborn->missingno) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\mvelazquez\appdata\local\anaconda3\envs\diplomado\lib\site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [56]:
import missingno as msno

In [ ]:
msno.matrix(df_total)

In [58]:
## renombre de columnas

short_name = {
'Noroeste PM10':'NO-PM10',    
}

df_total.rename(columns=short_name,inplace=True)

In [61]:
## nulos por año

nulos_año=df_total.isnull().groupby(df_total['Fecha'].year).sum

AttributeError: 'Series' object has no attribute 'year'

In [ ]:
def plot_time_series(df, variable, zones, ylabel, title, start_date=None, end_date=None):
    plt.figure(figsize=(15, 5))
    if start_date and end_date:
        df = df.loc[start_date:end_date]
    
    for zone in zones:
        column = f"{zone}-{variable}"
        if column in df.columns:
            plt.plot(df.index, df[column], label=column)
        else:
            print(f"Columna {column} no encontrada en el DataFrame")
    plt.xlabel('Fecha_Hora')
    plt.ylabel(ylabel)
    plt.title(title)
    plt.legend()
    plt.show()